In [7]:
from utils import *
#reading the data
dataset = pd.read_csv('../Detecting-Cyber-Attacks-Kaggle-Callenge/data/partial_labels.csv')
x,segments=dataset.axes
array=dataset.values
results_df = pd.DataFrame(columns=["id","label"])

In [8]:
for testUser in range(10,40):
    print("testUser = {}".format(testUser))
    z = np.reshape(array[testUser,1:],-1)
    Y_train = z[0:50]

    #read instructions
    fileName = array[testUser,0]
    path_read = "../Detecting-Cyber-Attacks-Kaggle-Callenge/data/FraudedRawData/User"+str(testUser)
    instructions = pd.read_csv(path_read, sep=" ", header=None)
    arr = np.reshape(instructions.values,(150,100))

    uniqe=set()
    strange=[]
    index=[]
    z=0
    x_train=[]

    index=0
    wordsCount={}
    countbackwrd= set()
    len_countbackwrd=[]
    word_lenght=[]
    count = 0
    mean_len=0
    uniqcheck=set()
    count_vec_all=[]
    count_vec_usr=[]
    vectorizer = TfidfVectorizer(min_df=0.4,ngram_range=(1,2))

    cout_len=0
    for i in range(150):
        Str=' '.join((arr[i,:]))
        if(i<50):
            count_vec_usr.append(' '.join(arr[i,:]))
            count_vec_all.append(' '.join(arr[i,:]))
        else:
            count_vec_all.append(' '.join(arr[i,:]))
    vectorizer.fit_transform(count_vec_all)
    X_all = vectorizer.transform(count_vec_all)
    X_all=X_all.toarray()
    X_usr = vectorizer.transform(count_vec_usr)
    X_usr=X_usr.toarray()


    for i in range(50):
        for j in range(100):
            uniqe.add(arr[i][j])
            for z in range(j,j+5):
                if(j%5==0 or j==0):
                    countbackwrd.add(arr[i][z])
            mean_len=len(countbackwrd)+mean_len
            cout_len=len(arr[i][j])+cout_len
            countbackwrd.clear()
        x_train.append([random.randint(0, 2)])
        mean_len=0
        cout_len=0
    mean_len=0
    count=0

    for i in range(50,150):
        for j in range(100):
            uniqcheck.add(arr[i][j])
            if (arr[i][j] not in uniqe):
                count = count + 1
            for z in range(j,j+5):
                if(j%5==0 or j==0):
                    countbackwrd.add(arr[i][z])
            mean_len=len(countbackwrd)+mean_len
            cout_len=len(arr[i][j])+cout_len
            countbackwrd.clear()
        strange.append([count])
        uniqcheck.clear()
        count = 0
        mean_len=0
        cout_len=0

    #train module
    #x_test=x_train+strange
    x_test=np.concatenate((x_train,strange))
    #x_test=np.c_[X_all,x_test]
    #x_train=np.c_[X_usr,x_train]
    clf= LocalOutlierFactor(n_neighbors=25,contamination=0.1, novelty=True)
    #clf = IsolationForest(behaviour='new', max_samples=20, contamination=0.5)
    #clf=EllipticEnvelope(support_fraction=1.,contamination=0.1)
    clf.fit(x_train)
    t=clf.predict(x_test)
    t[t == 1] = 0
    t[t == -1] = 1
    plt.show()
    print(X_usr)
    curr_user_results = t[50:150]
    curr_user_results_df = pd.DataFrame(columns=["id","label"])
    start_rows = 5000
    till_rows = 5100

    for i in range(curr_user_results.size):
        curr_user_results_df.loc[i] = ["User{}_{}-{}".format(testUser,start_rows,till_rows),curr_user_results[i]]
        start_rows = start_rows + 100
        till_rows = till_rows + 100
    results_df = results_df.append(curr_user_results_df)

fname = "out/submission_results_{}.csv".format(date.today())
results_df.to_csv(fname, index=False)

testUser = 10
[[0.         0.02998297 0.04010502 ... 0.04422804 0.         0.03923843]
 [0.14256782 0.15734556 0.21046438 ... 0.09284051 0.         0.1647333 ]
 [0.         0.13331691 0.03566476 ... 0.0393313  0.08809523 0.06978822]
 ...
 [0.09645422 0.12774252 0.17086755 ... 0.04710842 0.         0.1671754 ]
 [0.         0.16024482 0.         ... 0.03939633 0.22060225 0.        ]
 [0.05971332 0.11862514 0.05289073 ... 0.         0.         0.05174786]]
testUser = 11
[[0.10855791 0.07342789 0.13469209 ... 0.10855791 0.23004901 0.        ]
 [0.15237038 0.05153118 0.03781039 ... 0.05079013 0.         0.21225154]
 [0.21666986 0.08793248 0.12903881 ... 0.13000192 0.33059013 0.09054617]
 ...
 [0.         0.         0.38490123 ... 0.         0.         0.        ]
 [0.         0.         0.25063741 ... 0.         0.         0.        ]
 [0.12578796 0.12762327 0.09364206 ... 0.12578796 0.         0.1752223 ]]
testUser = 12
[[0.         0.11046797 0.         ... 0.         0.         0.0682309

[[0.07523485 0.         0.23972578 ... 0.08712495 0.         0.        ]
 [0.04058158 0.         0.19396166 ... 0.04699508 0.0419965  0.0419965 ]
 [0.04683984 0.         0.14924888 ... 0.0542424  0.09694592 0.09694592]
 ...
 [0.         0.         0.10189761 ... 0.         0.06618849 0.06618849]
 [0.04600643 0.06545046 0.18324166 ... 0.10655455 0.09522099 0.09522099]
 [0.05550013 0.07895656 0.17684376 ... 0.         0.05743521 0.05743521]]
testUser = 17
[[0.         0.         0.         ... 0.         0.27613304 0.        ]
 [0.         0.         0.         ... 0.         0.2284452  0.        ]
 [0.0975179  0.         0.11618488 ... 0.         0.52544469 0.        ]
 ...
 [0.         0.         0.         ... 0.         0.20661893 0.21646531]
 [0.         0.         0.         ... 0.         0.11723829 0.12282526]
 [0.02999056 0.         0.03573139 ... 0.         0.06059804 0.06348582]]
testUser = 18
[[0.16503394 0.17888162 0.         ... 0.         0.         0.15965032]
 [0.0191932

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.16109589 0.17235841 0.19248209 ... 0.         0.25145814 0.25145814]
 [0.19123265 0.20460209 0.11847649 ... 0.         0.27437812 0.27437812]
 [0.18611732 0.19912914 0.12972075 ... 0.         0.27730944 0.27730944]]
testUser = 21
[[0.         0.         0.11290818 ... 0.         0.         0.        ]
 [0.         0.         0.25095518 ... 0.         0.         0.        ]
 [0.         0.         0.20196219 ... 0.         0.         0.        ]
 ...
 [0.05072215 0.05106785 0.0669808  ... 0.03871572 0.03177664 0.03177664]
 [0.04556451 0.04587506 0.04011327 ... 0.03477895 0.02854546 0.02854546]
 [0.03769215 0.03794904 0.06636549 ... 0.         0.0472271  0.0472271 ]]
testUser = 22
[[0.0335878  0.         0.         ... 0.         0.06834188 0.07450677]
 [0.2638500

testUser = 29
[[0.         0.17598108 0.         ... 0.         0.         0.        ]
 [0.         0.02993105 0.         ... 0.         0.         0.        ]
 [0.         0.10844002 0.         ... 0.         0.         0.        ]
 ...
 [0.         0.06216613 0.         ... 0.         0.         0.        ]
 [0.05184506 0.13371201 0.         ... 0.05485225 0.09747711 0.05184506]
 [0.         0.05637888 0.         ... 0.         0.         0.        ]]
testUser = 30
[[0.         0.89311984 0.         ... 0.         0.         0.        ]
 [0.         0.4346026  0.         ... 0.         0.         0.        ]
 [0.         0.15387602 0.         ... 0.         0.         0.        ]
 ...
 [0.04701202 0.22005168 0.27507391 ... 0.21159532 0.0865216  0.11844813]
 [0.         0.21482814 0.26854426 ... 0.24936253 0.11765153 0.15032736]
 [0.04733682 0.22157198 0.23436291 ... 0.19175147 0.1088992  0.09541317]]
testUser = 31
[[0.02708145 0.02819723 0.04283049 0.12233547 0.33700932 0.11851409
  

testUser = 32
[[0.0711237  0.20127617 0.072348   ... 0.26006561 0.06822535 0.1364507 ]
 [0.05369107 0.18992846 0.05461528 ... 0.14724206 0.05150311 0.10300622]
 [0.05241551 0.07416651 0.05331777 ... 0.14374398 0.05027953 0.10055907]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.07388677 0.         ... 0.         0.         0.        ]]
testUser = 33
[[0.         0.22701667 0.11324984 ... 0.         0.         0.        ]
 [0.         0.20685581 0.06879491 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.02473878 0.02473878]
 [0.         0.01613694 0.         ... 0.02595512 0.         0.        ]
 [0.04240704 0.24513176 0.08152451 ... 0.         0.04491571 0.04491571]]
testUser = 34
[[0.10419947 0.14074882 0.47506766 ... 0.24631044 0.07920537 0.       

In [ ]:
#os.system('kaggle competitions submit -c detectingcyberattackscallenge -f "{0}" -m "{1}"'.format(fname, "Submitting results to kaggle"))